variables:
  BUILDX_VERSION: "v0.5.1"

stages:
  - test
  - build

shell check:
  image: koalaman/shellcheck-alpine:stable
  stage: test
  before_script:
    - shellcheck --version
  script:
    - shellcheck *.sh
  only:
    changes:
      - ./**/*.sh

# https://stackoverflow.com/a/58618830
build and push image:
  image: docker:19.03
  stage: build
  services:
    - docker:dind
  before_script:
    - mkdir -p ~/.docker/cli-plugins
    - wget -O ~/.docker/cli-plugins/docker-buildx "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64"
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker buildx create --use
    - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386 --tag "${CI_REGISTRY_IMAGE}/dokuwiki-fpm:latest" --push .
  only:
    - main
